/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BookingObjectPageObjectPage journey");

        opaTest("Navigate to BookingObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThePassengerListGenerated.onFilterBar().iExecuteSearch();
            Then.onThePassengerListGenerated.onTable().iCheckRows();
            When.onThePassengerListGenerated.onTable().iPressRow(0);

            Then.onThePassengerObjectPageGenerated.iSeeThisPage();
            Then.onThePassengerObjectPageGenerated.onTable({ property: "to_Booking" }).iCheckRows();
            When.onThePassengerObjectPageGenerated.onTable({ property: "to_Booking" }).iPressRow(0);

            Then.onTheBookingObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheBookingObjectPageGenerated.iCheckNumberOfSections(2);
        });

        opaTest("Check the Booking section of the Object Page", function (_Given, When, Then) {
            When.onTheBookingObjectPageGenerated.iGoToSection({ section: "Booking" });
            Then.onTheBookingObjectPageGenerated.iCheckSection({ section: "Booking" });
            Then.onTheBookingObjectPageGenerated.onForm({ section: "Booking" }).iCheckField({ property: "BookingID" });
            Then.onTheBookingObjectPageGenerated.onForm({ section: "Booking" }).iCheckField({ property: "to_Customer_CustomerID" });
            Then.onTheBookingObjectPageGenerated.onForm({ section: "Booking" }).iCheckField({ property: "BookingDate" });
            Then.onTheBookingObjectPageGenerated.onForm({ section: "Booking" }).iCheckField({ property: "BookingStatus_code" });
            Then.onTheBookingObjectPageGenerated.onForm({ section: "Booking" }).iCheckField({ property: "to_Carrier_AirlineID" });
            Then.onTheBookingObjectPageGenerated.onForm({ section: "Booking" }).iCheckField({ property: "ConnectionID" });
            Then.onTheBookingObjectPageGenerated.onForm({ section: "Booking" }).iCheckField({ property: "FlightDate" });
            Then.onTheBookingObjectPageGenerated.onForm({ section: "Booking" }).iCheckField({ property: "FlightPrice" });
        });

        opaTest("Check the to_BookSupplement::PresentationVariant section of the Object Page", function (_Given, When, Then) {
            When.onTheBookingObjectPageGenerated.iGoToSection({ section: "to_BookSupplement::PresentationVariant" });
            Then.onTheBookingObjectPageGenerated.iCheckSection({ section: "to_BookSupplement::PresentationVariant" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});